on:
  push:
    branches: [main]

name: Deploy to NPM

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install Dependencies
        run: npm ci --include=dev

      - name: Test
        run: |
          npx prettier --check .
          npm run lint -- --max-warnings 1
          npm test

      - name: Cleanup
        if: always()
        run: rm -Rf *

  build:
    needs: test
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Login
        env:
          NPM_USER: ${{ secrets.NPM_USER }}
          NPM_PASS: ${{ secrets.NPM_PASS }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NODE_ENV: production
        run: |
          npm install npm-cli-login -g
          npm-cli-login

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Cleanup
        if: always()
        run: rm -Rf *
    outputs:
      version: ${{ steps.release.outputs.version }}
